Reworkui
LeopoldoEstevezAgra/R004-Biblio-Guille pull request #1
Opened 2023-06-28 12:09 UTC by pinguille0027

cambios en los colores y diseño de elementos.

2023-06-30 04:33 UTC, LeopoldoEstevezAgra requested changes
La lógica guay pero intenta sobre todo trabajar en nombre de archivos, facilidad de lectura de código o consistencia en todo el código fuente (Idiomas, estilos ... ). Ayuda mucho cuando curras con otros desarrolladores

2023-06-30 04:33 UTC, LeopoldoEstevezAgra commented on components/atoms/PedirBoton.tsx
> +    <button className={small ? styles.sBotonPrim : styles.lBotonPrim}>
Está bien pero me parece un poco extraño pasar un boolean y hacer un ternario.

Una manera que yo haría es tener unos estilos y propiedades por defecto y pasar a un componente botón una sobreescritura de estilos. De esta forma solo haría falta 1 componente "Botón" que puedes usar en toda la app. Algo similar a : 

```tsx
// Archivo que usa botón

return (
   // ....
  <Boton className={styles.smallButton} />
)
```

```tsx
// Archivo /src/components/atoms/Button.tsx

interface IProps {
   className?: string;
   small?: boolean;
   onClick? = (e) => void;
   // ...
}


const Buton: React.FC<IProps> = ({
  className = styles.defaultButtonStyles,
  small = false,
  onClick
}) => {
  // Logica para añadir la clase de small a className si el prop es true
  return (
    <button 
       className={className}
       onClick={(e) => {onClick?.()}}  // Esto es ejecución condicional de funcion if undefined
    />
}
```

Esto hace que el componente sea mucho más reusable pero tu implementación está bien

2023-06-30 04:33 UTC, LeopoldoEstevezAgra commented on components/atoms/RoundedInput.tsx
> +          /*onChange={(e) => {
Intenta evitar pushear código con comentarios, en el caso de que sea temporal es recomendable añadir una nota del estilo: Comment reason: Disabled due to testing .

Si lo dejas comentado y luego raravez nos acordamos de la razón por la que está así y simplemente lo eliminamos o queda comentado siempre

2023-06-30 04:33 UTC, LeopoldoEstevezAgra commented on components/atoms/TarjetaCategoria.tsx
> +        <div className={small ? (enfasis ? `${styles.smallRound} ${styles.enfasis}` : `${styles.smallRound} ${styles.fondo}`) : (enfasis ? `${styles.round} ${styles.enfasis}` : `${styles.round} ${sty
No hagas ternarios anidados, me cuesta muchísimo leerlo. Sería mucho mejor: 
```tsx
const Something = () => {
  let parsedStyles = defaultValue;
  if (something && nestedCondition) {
    parsedStyles += 'algo';
  } else {
    parsedStyles = 'otraCosa';
  }
  return (
     <div className={parsedStyles} />
  )
};

```

Efectivamente es mucho más código pero de una pasada lo puedes leer de manera simple, incluso podrías mover los condicionales a variables separadas para hacer los if más simples si hay muchas variables que checkear

2023-06-30 04:33 UTC, LeopoldoEstevezAgra commented on pages/infolibro/[id].tsx
> +      <Link href="/" ><button className={styles.volver}>&lt;&lt;</button></Link>
Esto ya es un poco cosa de estilo mio y por ser pedante pero suelo poner cada componente en una linea
```tsx
<Link href="/" >
   <button className={styles.volver}>
      &lt;&lt;
   </button>
</Link>
```

Es un poco más facil de leer de pasada.

2023-06-30 04:33 UTC, LeopoldoEstevezAgra commented on pages/infolibro/[id].tsx
> +        <h2 className={styles.h2secc}>Libros recomendados</h2>
Acostumbrate a usar nombres de variables, clases etc más descriptivos. Un mejor nombre de estilo sería `styles.sectionSubtitle` por ejemplo

2023-06-30 04:33 UTC, LeopoldoEstevezAgra commented on styles/InfoLibro.module.css
Intenta usar mejores nombres de clase;
- volver qué es ? un botón o un cuadro de ayuda ? . Un mejor nombre sería volverButton
- Mejor recomendationContainer
- Mejor seccionSubtitle

E intenta usar o solo inglés o solo castellano. Ver "volver" y "card" seguidos es raro y no tiene ninguna consistencia

2023-06-30 04:33 UTC, LeopoldoEstevezAgra commented on styles/components/TarjetaLibro.module.css
Intenta usar unidades relativas cuando puedas como rem, em, % etc. Usando pixeles puedes hacer que en pantallas más pequeñas o más grandes que las tuyas se vea raro. 
Si quieres usar píxeles usalos en max/min-width por ejemplo, esto permite que se adapte algo más.

2023-06-30 04:33 UTC, LeopoldoEstevezAgra commented on styles/components/atoms/Corazones.module.css
Falta consistencia de idiomas con otros archivos.

2023-06-30 04:33 UTC, LeopoldoEstevezAgra commented on styles/components/atoms/botones.module.css
> +.lBotonPrim{
De nuevo, mejores nombres y más descriptivos

2023-06-30 04:33 UTC, LeopoldoEstevezAgra commented on components/atoms/Corazones.tsx
>          <Image key={index}
No es muy buena práctica usar el índice como key. En el caso de que el array se modifique el mismo key puede ir para otro elemento que pilla la posición de otro. Idealmente debes de usar una parte única de la información.

En este caso como son corazones es aceptable pero recomendaría cambiarlo por 5 imágenes diferentes 
```tsx
const heartNumber = de 1 a 5
return(
  <Image src={`/path/to/images/hearts-${heartNumber}` alt={`${heartNumber}-hearts`}} />
)
```

Además esta solución es bastante mejor para lectores de pantalla y para trabajar con responsive layout

2023-06-30 04:33 UTC, LeopoldoEstevezAgra commented on components/atoms/InfBoton.tsx
Mejores nombres de ficheros. En vez de InfBoton arreglas mucho mejor con InformationButton o BotonInformacion dependiendo del idioma que uses para el nombre de ficheros.

Lo mismo que el comentario para PedirBoton. Estes 2 archivos puedes juntarlos en 1 con un botón genérico.

2023-07-01 13:54 UTC, pinguille0027 commented on components/atoms/PedirBoton.tsx
> +    <button className={small ? styles.sBotonPrim : styles.lBotonPrim}>
el on click ya lo estas dejando listo para despues no? Duda que tengo es que realmente solo voy a tener dos posibles clases para el botón. la larga y la pequeña. Con lo que me pasas realmente me permite en cada pagina donde lo uso otorgale una clase, los estilos los cogería del css del componente o tendría que hacerlos en la pagina donde se le otorga la clase?

2023-07-04 17:17 UTC, LeopoldoEstevezAgra requested changes
Consitencia de nombres y tabs ....

2023-07-04 17:17 UTC, LeopoldoEstevezAgra commented on components/TarjetaLibro.tsx
> +          <TarjetaCategoria color='enfasis' key={categoria.id} nombreCategoria={categoria.nombre} />
Enfasis no es un color

2023-07-04 17:17 UTC, LeopoldoEstevezAgra commented on components/TarjetaLibro.tsx
> +          <TarjetaCategoria color='enfasis' key={categoria.id} nombreCategoria={categoria.nombre} />
O pones comillas simples o pones comillas dobles pero solo una de ellas

2023-07-04 17:17 UTC, LeopoldoEstevezAgra commented on components/TarjetaLibroMini.tsx
> +                        <TarjetaCategoria size='small' color='fondo' key={categoria.id} nombreCategoria={categoria.nombre} />
Comillas y 'fondo' no es un color, es un modo

2023-07-04 17:17 UTC, LeopoldoEstevezAgra commented on pages/infolibro/[id].tsx
Porqué los hay tantos espacios entre los imports ?

2023-07-04 17:17 UTC, LeopoldoEstevezAgra commented on pages/infolibro/[id].tsx
> +              <TarjetaCategoria color='fondo' key={categoria.id} nombreCategoria={categoria.nombre} />
Fondo no es un color, y las comillas todas iguales

2023-07-04 17:17 UTC, LeopoldoEstevezAgra commented on pages/infolibro/[id].tsx
>            return (<TarjetaLibroMini key={index} book={book}></TarjetaLibroMini>)
Tabs correctas porfa

2023-07-04 17:17 UTC, LeopoldoEstevezAgra commented on styles/InfoLibro.module.css
> +.botonVolver{
Castellano o ingles !

2023-07-04 17:17 UTC, LeopoldoEstevezAgra commented on styles/InfoLibro.module.css
>  .sinopsis{
Castellano o inglés ! !

2023-07-04 17:17 UTC, LeopoldoEstevezAgra commented on styles/components/TarjetaLibro.module.css
2 o 4 espacios !!!!!!!!

2023-07-04 17:17 UTC, LeopoldoEstevezAgra commented on styles/components/TarjetaLibroMini.module.css
2 o 4 espacios !!!!!!!!

2023-07-04 17:17 UTC, LeopoldoEstevezAgra commented on styles/components/atoms/botones.module.css
> +.largeBotonPrimario{
Auch

2023-07-04 17:17 UTC, LeopoldoEstevezAgra commented on styles/components/atoms/botones.module.css
> +.smallBotonPrimario{
Auch

2023-07-08 09:02 UTC, LeopoldoEstevezAgra approved these changes
Mucho mejor, aún hay algún punto en el que está mezclado ingles y castellano pero por regla general ahora está más o menos estandarizado.

Revisa lo de separar los tipos a su propia carpeta para estandarizar interfaces, types o firmas de función

2023-07-08 09:02 UTC, LeopoldoEstevezAgra commented on pages/index.tsx
Lo mismo de antes, procura separar tipos reutilizados a sus propios ficheros compartidos, a eso se le llama principio DRY ( Dont repeat yourself )

2023-07-08 09:02 UTC, LeopoldoEstevezAgra commented on pages/infolibro/[id].tsx
> +        const getLibro = async () => {
No me suelen gustar los try / catch en el useEffect. Prueba a separar estas cosas en un nuevo hook que no genere excepción

2023-07-08 09:05 UTC, LeopoldoEstevezAgra commented
Está guay ahora, te lo mergeo pero revisate las notas que te puse

2023-07-08 09:05 UTC, merged